name: Raymond Redfern Photography
favicon: null
layout_spectrum: 0.507172980112955
typography_spectrum: 0.7636030598077923
title: Raymond RedfernPhotography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#393939'
    - '#838383'
    - '#8f10ff'
    - '#a146fe'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
